os: osx
osx_image: xcode10
branches:
  only:
    - master

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Azure.xcworkspace
  - AZURECORE=AzureCore
  - AZUREAUTH=AzureAuth
  - AZUREDATA=AzureData
  - AZUREPUSH=AzurePush
  - AZURESTORAGE=AzureStorage
  - IOS_FRAMEWORK_SCHEME="iOS"
  - MACOS_FRAMEWORK_SCHEME="macOS"
  - TVOS_FRAMEWORK_SCHEME="tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="watchOS"
  matrix:
    - AZURE_SDK="$AZUREAUTH"    DESTINATION="OS=12.0,name=iPhone XS"                  SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREAUTH"    DESTINATION="OS=10.3.1,name=iPhone 7"                 SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREAUTH"    DESTINATION="arch=x86_64"                             SCHEME="$MACOS_FRAMEWORK_SCHEME"   RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREAUTH"    DESTINATION="OS=12.0,name=Apple TV"                   SCHEME="$TVOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREAUTH"    DESTINATION="OS=5.0,name=Apple Watch Series 4 - 44mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" RUN_TESTS="NO"  POD_LINT="NO"

    - AZURE_SDK="$AZUREDATA"    DESTINATION="OS=12.0,name=iPhone XS"                  SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREDATA"    DESTINATION="OS=10.3.1,name=iPhone 7"                 SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREDATA"    DESTINATION="arch=x86_64"                             SCHEME="$MACOS_FRAMEWORK_SCHEME"   RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREDATA"    DESTINATION="OS=12.0,name=Apple TV"                   SCHEME="$TVOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREDATA"    DESTINATION="OS=5.0,name=Apple Watch Series 4 - 44mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" RUN_TESTS="NO"  POD_LINT="NO"

    - AZURE_SDK="$AZUREPUSH"    DESTINATION="OS=12.0,name=iPhone XS"                  SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREPUSH"    DESTINATION="OS=10.3.1,name=iPhone 7"                 SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREPUSH"    DESTINATION="arch=x86_64"                             SCHEME="$MACOS_FRAMEWORK_SCHEME"   RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREPUSH"    DESTINATION="OS=12.0,name=Apple TV"                   SCHEME="$TVOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZUREPUSH"    DESTINATION="OS=5.0,name=Apple Watch Series 4 - 44mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" RUN_TESTS="NO"  POD_LINT="NO"

    - AZURE_SDK="$AZURESTORAGE" DESTINATION="OS=12.0,name=iPhone XS"                  SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZURESTORAGE" DESTINATION="OS=10.3.1,name=iPhone 7"                 SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZURESTORAGE" DESTINATION="arch=x86_64"                             SCHEME="$MACOS_FRAMEWORK_SCHEME"   RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZURESTORAGE" DESTINATION="OS=12.0,name=Apple TV"                   SCHEME="$TVOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO"  POD_LINT="NO"
    - AZURE_SDK="$AZURESTORAGE" DESTINATION="OS=5.0,name=Apple Watch Series 4 - 44mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" RUN_TESTS="NO"  POD_LINT="NO"

cache:
  directories:
  - "$AZURECORE/Carthage"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --project-directory "$AZURECORE" --verbose --no-use-binaries --cache-builds

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$AZURE_SDK $SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$AZURE_SDK $SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$AZURE_SDK $SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$AZURE_SDK $SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
